version: '3'

services:
  api:
    image: sword-health_api:latest
    container_name: "docker_api"
    ports:
      - "8081:3000"
  db:
    image: mysql
    command: --init-file /data/application/init.sql
    volumes:
        - ./scripts/init.sql:/data/application/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234